name: Cypress Tests
on:
  pull_request:
    branches:
      - master

jobs:
  cypress-test:
    name: Cypress tests
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ci_node_index: [0,1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install yarn and system libraries
        run: |
          npm install -g yarn
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install dependencies
        run: yarn install
      - name: Run cypress test
        env:
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
        continue-on-error: true
        run: ./run-tests-in-parallel.sh